# Generated by Django 5.0.6 on 2026-06-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_hit",
            field=models.BooleanField(default=False, verbose_name="Хит"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Новинка"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_sale",
            field=models.BooleanField(default=False, verbose_name="Товар по акции"),
        ),
    ]
